src/constants.sv
src/one_bit/full_adder.sv
src/one_bit/multiplexer.sv
src/one_bit/nor_gate.sv
src/one_bit/xnor_gate.sv
src/one_bit/or_gate.sv
src/one_bit/switch.sv
src/one_bit/not_gate.sv
src/one_bit/half_adder.sv
src/one_bit/nand_gate.sv
src/one_bit/and_gate.sv
src/one_bit/xor_gate.sv
src/multi_bit/sll.sv
src/multi_bit/substractor_multi.sv
src/multi_bit/decrementor_multi.sv
src/multi_bit/sra.sv
src/multi_bit/and_multi.sv
src/multi_bit/incrementor_multi.sv
src/multi_bit/full_adder_multi.sv
src/multi_bit/slt_multi.sv
src/multi_bit/sltu_multi.sv
src/multi_bit/xor_multi.sv
src/multi_bit/or_multi.sv
src/multi_bit/srl.sv
src/multi_bit/invertor_multi.sv
src/multi_bit/xnor_multi.sv
src/elements/mux_4op.sv
src/elements/arithmetic_unit.sv
src/elements/mux_2op.sv
src/elements/logic_unit.sv
src/elements/mux_1op.sv
src/elements/decoder_5_32.sv
src/memory/sr_latch.sv
src/memory/d_latch.sv
src/memory/register_multi.sv
src/memory/d_flip_flop.sv
src/riscv32i/memory.sv
src/riscv32i/alu.sv
src/riscv32i/imm_decoder.sv
src/riscv32i/register_file.sv
src/riscv32i/program_counter.sv
src/riscv32i/control_unit.sv
src/riscv32i/branching.sv
tb/riscv32/branching_tb.sv
