module pll_led (
    input  logic clock_25Mhz, 
    input  logic rst_n,
    output logic led_12_5,     //  12.5 МГц
    output logic led_25,       //  25 МГц
    output logic led_50,       //  50 МГц
    output logic led_100,      //  100 МГц
    output logic led_200       //  200 МГц
);

    logic pll_clk_400; 
    logic pll_locked;
    logic sys_reset;

    //autogenerated
    pll_400 pll (
        .reset   (1'b0),       
        .clk_in  (clock_25Mhz),
        .clk_out (pll_clk_400),  
        .locked  (pll_locked)
    );

    //common reset
    logic rst_n_stable_1 = 0;
    logic rst_n_stable_2 = 0;

    assign sys_reset = !pll_locked || rst_n_stable_2;

    logic [30:0] main_counter = 0;

    always_ff @(posedge pll_clk_400) begin
        if (sys_reset) begin
            main_counter <= '0;
            rst_n_stable_1 <= '0;
            rst_n_stable_2 <= '0;
        end else begin
            rst_n_stable_1 <= !rst_n;
            rst_n_stable_2 <= rst_n_stable_1;
            main_counter <= main_counter + 1'b1;
        end
    end
    assign led_200  = main_counter[29]; 
    assign led_100  = main_counter[28]; 
    assign led_50   = main_counter[27]; 
    assign led_25   = main_counter[26]; 
    assign led_12_5 = main_counter[25];

endmodule
